snowflake_password = <ENTER_THE_PASSWORD_HERE>

[connections.personal_snowflake]
account = "EFOMYZW-HKB80309"
user = "STREAMLIT_USER"
role = "STREAMLIT_ROLE"
warehouse = "STREAMLIT_WH"
database = "STREAMLIT__RESOURCE_MANAGEMENT"
schema = "ADMIN"